# Generated by Django 4.1.2 on 2024-05-04 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_alter_order_options_order_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='total_price',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product_name',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_id',
            field=models.ForeignKey(default='PID0000', on_delete=django.db.models.deletion.CASCADE, to='shopping.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ShoppingCartItem',
        ),
    ]
